-- RECREATE TABLEs BECAUSE I FORGOT TO SAVE AND I SCROLLED RIGHT AND IT WENT BACK
--NOW I HAVE TO MAKE EVERYTHING AND SAVE AT EVERY TABLE SO I WONT FORGET
--DID I MENTION I HAVE TO DO THIS AGAIN? AHHHH!!!

-- CREATE departments table (2nd try)
CREATE TABLE departments (
	dept_no VARCHAR,
	dept_name VARCHAR
);

-- CREATE dept_emp table
CREATE TABLE dept_emp (
	emp_no INT,
	dept_no VARCHAR
);

--
